//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseFunction_TableDrivedEntity
    {
        public DatabaseFunction_TableDrivedEntity()
        {
            this.DatabaseFunction_TableDrivedEntity_Columns = new HashSet<DatabaseFunction_TableDrivedEntity_Columns>();
        }
    
        public int ID { get; set; }
        public int DatabaseFunctionID { get; set; }
        public int TableDrivedEntityID { get; set; }
    
        public virtual DatabaseFunction DatabaseFunction { get; set; }
        public virtual ICollection<DatabaseFunction_TableDrivedEntity_Columns> DatabaseFunction_TableDrivedEntity_Columns { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
    }
}
